compare_turn_num: 2
dropout: 0.1
test_interval: 0.01
no_hard_negative: false
valid_during_training: false
no_inner_session_negative: true
compare_set_size: 10
gray_cand_num: 2

# train configuration
train:
    lr: 0.00003
    grad_clip: 1.0
    seed: 0
    batch_size: 64
    ctx_max_length: 128
    res_max_length: 32
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: bert-fp/best_bert-base-chinese.pt
        # path: bert-fp-comp/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    # must be one (because of the fully compare)
    batch_size: 1
    ctx_max_length: 128
    res_max_length: 32
    max_len: 288
