# rank: bert-ft-compare
rank: null
nhead: 6
dim_ffd: 1024
dropout: 0.1
num_encoder_layers: 4
gray_cand_num: 2
test_interval: 0.001

# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 64
    max_len: 256
    res_max_len: 64
    epoch: 5
    # no wamrup, set 0.0 (BERT-FP and UMS_BERT)
    warmup_ratio: 0.05
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        # path: bert-fp/best_bert-base-chinese.pt
        path: bert-fp-mono/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64
