full_turn_length: 100
test_interval: 0.01

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 1.0
    seed: 0
    batch_size: 128
    max_len: 64
    epoch: 5
    warmup_ratio: 0.
    stop_train: false
    stop_train_trigger:
        R10@1: 35.
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: bert-fp/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 64

# inference configuration
inference:
    seed: 0
    batch_size: 128 
    max_len: 64
    topk: 20
    index_type: Flat
    index_nprobe: 5
    dimension: 768
