rank: null
gray_cand_num: 5
lambda: 0.5
temp: 1.0

# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 32
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: bert-fp/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64

# inference configuration
inference:
    seed: 0
    batch_size: 128 
    max_len: 64
    topk: 20
    # index_type: IVF3722,Flat
    # index_type: IVF6509,Flat
    index_type: Flat
    dimension: 768
