# basic configuration for building the model
tokenizer: 
    zh: uer/gpt2-chinese-cluecorpussmall
pretrained_model: 
    zh: uer/gpt2-chinese-cluecorpussmall

# test configuration
test:
    seed: 0
    batch_size: 32
    max_len: 256
