dropout: 0.1

# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 64
    max_len: 256
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: bert-fp/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
