smoothing: 0.1

# train configuration
train:
    lr: 0.0005
    grad_clip: 1.0
    dropout: 0.1
    seed: 50
    batch_size: 64
    max_len: 256
    res_max_len: 64
    epoch: 10
    warmup_ratio: 0.1
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: true 

# test configuration
test:
    seed: 50
    batch_size: 1
    max_len: 256
    res_max_len: 64
    max_generate_length: 64
    min_generate_length: 12

